### ISSUE TITLE
Can't pass openstack provider from root

### ISSUE THREAD

**Issue by gavvvr** [ovh/terraform-ovh-publiccloud-network#1]
Hi. I try to use this project as terraform module. I declare a it like this:

```
module "network" {
  source = "ovh/publiccloud-network/ovh"

  providers = {
    ovh = "ovh.ovh"
    openstack = "openstack.ovh"
  }
...
}
```

And it gets downloaded with `terraform init`. As you can see I try to explicitly pass provider which I declared in my root module:

```
provider "openstack" {
  auth_url = "https://auth.cloud.ovh.net/v3" # Authentication URL
  domain_name = "default" # Domain Name - Always "default" for OVH
  alias = "ovh"
  region = "${var.region}"
  user_name   = "${var.user_name}"
  password    = "${var.password}"
}
```

The problem is that `terraform plan` gives me:

> Error: Error running plan: 1 error(s) occurred:
>
> * module.network.provider.openstack: One of 'auth_url' or 'cloud' must be specified

I think it happens because of `provider "openstack"` is already defined here in `main.tf`.
If I comment it, the provider from my root is successfully used. 

I also noticed that terraform tries to apply everything from examples directory of this module which is not my goal.

So, what is the correct use of this module? I would like to pass my own provider and do not get examples applied from here.

Looks like the most suitable options to use this module is to copy `main.tf` from here to my repo. But Terraform registry and documentation tells me that I just should declare it with `source = "ovh/publiccloud-network/ovh"`

Thanks

**Comment by yanndegat** [comment]
hi @gavvvr 

you're perfectly right on the "provider" issue.
i've already fixed this on other modules. even thought i fixed this one a long ago.
i'll fix this right away.

on the "examples" issue though, i've never noticed such behavior.
we should dig this a little bit further.

could you provide more info on the versions of terraform you're using for a start?

thanks a lot

**Comment by CoericK** [comment]
For me it was working fine but now im getting the error `* provider.openstack: One of 'auth_url' or 'cloud' must be specified` what should I do to fix this? I didnt add any  other provider

**Comment by megakoresh** [comment]
@yanndegat This issue has not been fixed, please reopen:

```hcl
provider "openstack" {
  auth_url    = "https://s1.api.os.fi:13000"
  tenant_name = "phs-prod-sd"
  alias       = "s1"
}

resource "openstack_networking_router_v2" "router" {
  name                = "at-rere-router"
  admin_state_up      = true
  external_network_id = data.openstack_networking_network_v2.external_network.id

  provider = openstack.s1
}
```

Environment:

```sh
$ env |grep OS_
OS_USER_DOMAIN_NAME=mycorp
OS_IDENTITY_API_VERSION=3
OS_PASSWORD=mypass
OS_AUTH_TYPE=password
OS_USERNAME=myemail@mycorp.com
OS_NO_CACHE=True
OS_PROJECT_DOMAIN_NAME=mycorp
```

Output: 

```
Error: One of 'auth_url' or 'cloud' must be specified

  on <empty> line 0:
  (source code not available)
```
